version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      .env
    volumes:
      - ./tmp/db:/var/lib/mysql
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    env_file:
      .env
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
